# Generated by Django 4.1.2 on 2023-02-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='disqauted_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
