# Generated by Django 4.1.2 on 2023-03-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_customer_orderplaced_product_delete_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T', 'T_Shirt'), ('H', 'Hoodies'), ('CT', 'Coding_Tshirt'), ('AT', 'Anime_Thirt')], max_length=5),
        ),
    ]
